### ISSUE TITLE
usage from dune

### ISSUE THREAD

**Issue by joprice** [dbuenzli/useri#3]
I built this project with nix and then tried to use it in a dune project, and got the following error:

```
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Useri_backend referenced from /nix/store/l6ff6bjd7clj54bbwxdzp8hvvi4qh8cl-useri/lib/ocaml/4.10.0/site-lib/useri/useri.cmxa(Useri)
```

Other projects gg, tgls, tsdl all built, so I'm wondering if backend selection in this project requires some extra build configuration. I'm using the topkg helper here https://github.com/NixOS/nixpkgs/blob/e7fe577d9803885d1191c6612b95c246cb605dde/pkgs/development/ocaml-modules/topkg/default.nix#L20-L26 to build it.

**Comment by dbuenzli** [comment]
You need to select and link the backend (`useri.tsdl` or `useri.jsoo`) before `useri.cmxa`.

**Comment by joprice** [comment]
I tried changing the order of appearance in the libraries list, with useri.tdsl appearing first, and was greeted with a new error:

```
Error: Files /nix/store/f4cwg18v9k7b0vwk8nz5h14i34113kqs-useri/lib/ocaml/4.10.0/site-lib/useri/useri.cmxa
       and /nix/store/f4cwg18v9k7b0vwk8nz5h14i34113kqs-useri/lib/ocaml/4.10.0/site-lib/useri/tsdl/useri_tsdl.cmxa
       make inconsistent assumptions over interface Useri_backend
```

I'm not sure how to go about debugging that.

**Comment by dbuenzli** [comment]
I tried to push a few build fixes. Could you see if it improves.

**Comment by joprice** [comment]
Works! Thank you for the Christmas vortex!
